name: mqtt_page
multiply: false
containers:
  - name: mqtt_page
    config:
        restart: always
        ports: []
        volumes: []
        labels: []
        depends_on: 
          - rabbitmq.service_healthy